language: erlang
script: make all test
notifications:
  webhooks: http://basho-engbot.herokuapp.com/travis?key=622369a511690ee1a7fe54c44eebb57dc8e24b5f
  email: eng@basho.com
otp_release:
  - 18.3
  - 17.5
  - R16B03
  - R15B03
